[package]
name = "CSC201-Rust"
version = "0.1.0"
authors = ["Josh Johnson <joshdjohnson2217@gmail.com"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
scanner-rust = "2.0.15"